### ISSUE TITLE
Can't download large backup file

### ISSUE THREAD

**Issue by nladev** [pavel-mironchik/laravel-backup-panel#13]
I can't download large file above 1GB .But < 1 GB is completely ok.
let me know how should I do.

Browser Error Message is ->
This site can’t be reachedThe webpage at http://192.168.3.3/backup/api/download-backup?disk=local&path=something/2020-07-01-10-46-53.zip might be temporarily down or it may have moved permanently to a new web address.

**Comment by pavel-mironchik** [comment]
@CrackiGuy could it be an insufficient memory issue? Is there any error in a Laravel's log?

**Comment by pavel-mironchik** [comment]
@CrackiGuy feel free to open the issue again when you have additional information.
