### ISSUE TITLE
support Laravel 5.5.*

### ISSUE THREAD

**Issue by djoudi** [pavel-mironchik/laravel-backup-panel#2]
Problem 1
    - Installation request for pavel-mironchik/laravel-backup-panel ^1.3 -> satisfiable by pavel-mironchik/laravel-backup-panel[v1.3.0].
    - pavel-mironchik/laravel-backup-panel v1.3.0 requires spatie/laravel-backup ^6.7 -> satisfiable by spatie/laravel-backup[6.7.0, 6.7.1, 6.7.2, 6.7.3, 6.7.4, 6.7.5, 6.7.6] but these conflict with your requirements or minimum-stability.

**Comment by pavel-mironchik** [comment]
Hey.

The spatie/laravel-backup v6 [requires](https://docs.spatie.be/laravel-backup/v6/requirements/) PHP 7.2, with the ZIP module and **Laravel 5.8 or higher**.

There is no plan 😞 to support the spatie/laravel-backup v5 which [can work](https://docs.spatie.be/laravel-backup/v5/requirements/) with Laravel 5.5 or higher. Still, you can fork the repository and try to adjust the code to work with spatie/laravel-backup v5.

Anyway, let me know if you will notice problems with Laravel 5.8.
