### ISSUE TITLE
Error change route

### ISSUE THREAD

**Issue by Oxicode** [pavel-mironchik/laravel-backup-panel#26]
![image](https://user-images.githubusercontent.com/1320709/109252581-eb960800-77bb-11eb-9a99-18328a7cf6b7.png)
Laravel 8

**Comment by Oxicode** [comment]
When return path in route, its ok

![image](https://user-images.githubusercontent.com/1320709/109252651-0bc5c700-77bc-11eb-8fcc-5ceaa2a6a5b1.png)

**Comment by pavel-mironchik** [comment]
@Oxicode do you mean that you changed the `path` value in the `config/laravel_backup_panel.php` file to `admin/backup`?

**Comment by Oxicode** [comment]
When 'path' is 'backup' its ok, but when path is '/admin/backup' its fails
![image](https://user-images.githubusercontent.com/1320709/109404087-bb23aa80-7930-11eb-9b90-f14ba8653d3f.png)

**Comment by pavel-mironchik** [comment]
I assume that you use version 1 of the package. Use version 2 instead.

Or, would you please create a PR fixing this issue for version 1?

**Comment by Oxicode** [comment]
PR fix?
