### ISSUE TITLE
Possible bug : undefined Backup::size() 

### ISSUE THREAD

**Issue by AEK-BKF** [pavel-mironchik/laravel-backup-panel#29]
Hello,
I installed the package with fresh Laravel 8.12, so I'm getting this error :
` Call to undefined method Spatie\Backup\BackupDestination\Backup::size()`
NB: the backup passes successfully but in the panel that error appears.

**Comment by AEK-BKF** [comment]
I got it, you need to rename the function which calculates the backup size : 
`size => sizeInBytes`

**Comment by pavel-mironchik** [comment]
@AEK-BKF would you please test the `l8-compatibility` branch? I don't use PHP8 and Laravel 8 yet.

**Comment by lloricode** [comment]
same here

php                                                                    v8.0.5 
laravel/framework                                              v8.41.0 
pavel-mironchik/laravel-backup-panel               2.1.0




> @AEK-BKF would you please test the `l8-compatibility` branch? I don't use PHP8 and Laravel 8 yet.

will try this

**Comment by lloricode** [comment]
> @AEK-BKF would you please test the `l8-compatibility` branch? I don't use PHP8 and Laravel 8 yet.

working as expected, tested on our site

**Comment by alcarazolabs** [comment]
Hi this bug was fixed? or only happens using php8?

**Comment by pavel-mironchik** [comment]
> Hi this bug was fixed? or only happens using php8?

It's fixed
