### ISSUE TITLE
Protect route /backup

### ISSUE THREAD

**Issue by alcarazolabs** [pavel-mironchik/laravel-backup-panel#34]
Hi I would like protect the route /backup to only auth users. I have created a route in the web.php which has the routes of the project.

```
Route::group([
    'middleware' => 'auth',
    'prefix'     => '/admin',
    'as'         => 'admin.'
], function () {

   Route::get('/backup', [BackupController::class, 'index'])->name("backup");
  ...
  ...
 other routes...

});
```
By the moment in local mode or debug mode any users that knows the route /backup can access and make backups, I have added that route and only works redirecting to login when the user  go to /admin/backup, but if him go directly to /backup can access and does not matter if him did login, how I can prevent it? 

My idea after fix it create the roles and permissions using laravel spatie permission package and I need to create slugs to each permission like 'admin.backup', admin.user.index etc.. I don't wan restrict this route by using and email of the auth user my idea is restrict this route by using role and permissions but first I want restrict this route to only auth users, by the moment anyone hwo knows the route /backup can access and make backups.

**Update**
After write this issue, I fixed the problem. I found the file web.php inside of vendor->pavel-mironchik->laravel-backup-panel->routes->web.php and I added the middleware auth to default route:

```
<?php
use Illuminate\Support\Facades\Route;

Route::view('/', 'laravel_backup_panel::layout')->middleware('auth')->name("backup.index");

```
Of this way only auth users can access that route.
Now Using the middleware 'can' for permissions I should do something like this:

`Route::view('/', 'laravel_backup_panel::layout')->middleware('can:admin.backup.index')->middleware('auth')->name("backup.index");
`
Of this way I think that only the users with the permission `admin.backup.index` could access to the routes /backup 
Is correct this? I'm not laravel expert, sorry.
I think that it's correct because I have one inframe calling the route 'backup.index' and by the moment the access is restricted:

![image](https://user-images.githubusercontent.com/7144988/134786121-90eea31b-cb36-4118-8bf4-ae14ecf893c2.png)

thanks so much.

**Comment by pavel-mironchik** [comment]
>By the moment in local mode or debug mode any users that knows the route /backup can access and make backups, I have added that route and only works redirecting to login when the user go to /admin/backup, but if him go directly to /backup can access and does not matter if him did login, how I can prevent it?

In the `local` environment, anyone can access that route, cause it doesn't make sense to restrict access in your own controlled environment.

>I found the file web.php inside of vendor->pavel-mironchik->laravel-backup-panel->routes->web.php and I added the middleware auth to default route:

After an update, you'll lose your adjustments, cause it's a vendor file.

I don't know if your solution actually works or is secure. I'd stick to the documentation and do this:

1. Change the path in `config/laravel_backup_panel.php` to `'path' => 'admin/backup',`.
2. Since you don't use a nullable type-hint for the `$user` in the authorization gate, you're guaranteed that a user is logged in:

```php
protected function gate()
{
    Gate::define('viewLaravelBackupPanel', function ($user) {
        // a user is already logged in here
    });
}
```

3. In the authorization gate, you may provide any logic, including checking for permission:

```php
protected function gate()
{
    Gate::define('viewLaravelBackupPanel', function ($user) {
        return $user->can('admin.backup.index');
    });
}
```

Probably, reading Laravel's documentation about gates would help too: https://laravel.com/docs/8.x/authorization#gates
Don't miss this part: https://laravel.com/docs/8.x/authorization#guest-users

**Comment by alcarazolabs** [comment]
> In the `local` environment, anyone can access that route, cause it doesn't make sense to restrict access in your own controlled environment.

Hi thanks for the reply! I'm testing the package Spatie Laravel-Permission. I did what you recommend to write inside of the gate function. However after migrate my database with seeders and permissions, the middleware added `$user->can('admin.backup.index');` does not did effect, anyone can access and the route is open to anyone. You say that it will be locked when I run `npm run production` or when I will upload the project to hosting in production? 

I modded the file web.php in the vendor directory because was the unique way of protect this route but you say that it can disappear when I trying of update the package in future versions? 

Thanks

**Comment by pavel-mironchik** [comment]
Nope, it has nothing with NPM. Check this out: https://laravel.com/docs/8.x/configuration#environment-configuration

>it can disappear when I trying of update the package in future versions

Exactly. Also, how do you plan to deploy such changes? By keeping the `vendor` folder in your repository?

**Comment by alcarazolabs** [comment]
> Nope, it has nothing with NPM. Check this out: https://laravel.com/docs/8.x/configuration#environment-configuration
> 
> > it can disappear when I trying of update the package in future versions
> 
> Exactly. Also, how do you plan to deploy such changes? By keeping the `vendor` folder in your repository?

Hi dear.. Yes I'm deploying the project to a shared hosting with the vendeor folder.. But when I added `return $user->can('admin.backup.index');` to the gate it, the route /backup continues being open to anyone, I'm worrie because I want protect it,, I also tried `->permission('admin.backup.index');` and does not work.
I deployed my project without did `npm run prod`.

**Comment by pavel-mironchik** [comment]
Well, it seems that you didn't change your environment. You have to set the `APP_ENV` variable in the `.env` file to `production`.

**Comment by alcarazolabs** [comment]
> Well, it seems that you didn't change your environment. You have to set the `APP_ENV` variable in the `.env` file to `production`.

Hi, I forgot do that, but now I changed it, however I'm getting a `403 FORBIDDEN` Alert:

![image](https://user-images.githubusercontent.com/7144988/135725132-83dbe2d1-dcca-4661-b78a-20abcb1f48c1.png)

My `.env` file now has:
APP_ENV=production
APP_DEBUG=false

After mod it I cleaned caches. `php artisan config:clear` and anothers commands..
```
php artisan log:clear
php artisan config:clear
php artisan config:cache
php artisan clear-compiled
php artisan route:clear
php artisan view:clear
php artisan cache:clear
composer dump-autoload -o
php artisan route:cache
php artisan optimize
php artisan optimize:clear

```
I tested the gate with the `email` of the user and the middleware `can`.
```
return in_array($user->email, [
                'myadminemail@mail.com'
            ]);

```
And I also tested:
`return $user->can('admin.backup.index');
`
The permission was inserted in the database and works because I can acces to my route: 

`  Route::get('admin/backup', [BackupController::class, 'index'])->name("backup.index");
`
I have not chaged the file in config/laravel_backup_panel.php the route is the default `backup/`.

If I put the project in debug mode and local mode the route is open but when I changed to production the `APP_ENV` I'm getting the 403 message.

**Comment by pavel-mironchik** [comment]
This is exactly how the gate works - you receive the 403 error in the production environment. So the gate actually works as expected and the question now is why you can't access the backup panel.

I recommend you starting from scratch - create a new project and make sure you can access the backup panel in the production environment using a constraint on the user's email first. Then add other packages for permissions.

**Comment by alcarazolabs** [comment]
> This is exactly how the gate works - you receive the 403 error in the production environment. So the gate actually works as expected and the question now is why you can't access the backup panel.
> 
I logged with one user that has the same email of the function of the gate and I got the same error `404 | Forbidden`

    protected function gate()
    {
        Gate::define('viewLaravelBackupPanel', function ($user) {
            return in_array($user->email, [
                'adminuser@gmail.com'
            ]);
         
        });
    }
}
This is not working with Laravel 8. The project now is in production mode. What should I do?

**Comment by pavel-mironchik** [comment]
I recommend you start from scratch - create a new project and make sure you can access the backup panel in the production environment using a constraint on the user's email first. Then add other packages for permissions.

**Comment by alcarazolabs** [comment]
> I recommend you start from scratch - create a new project and make sure you can access the backup panel in the production environment using a constraint on the user's email first. Then add other packages for permissions.

This looks rare. I now I'm developing another project without roles and permissions packages, now I only installed the package and I  modified the authorization gate in the app/Providers/LaravelBackupPanelServiceProvider.php putting my gmail email which belogns to my user account of the project and again I'm getting `403 | Forbidden` I don't know what should do now again. Please verify it.
Note. I setted this two variables to
APP_ENV=production
APP_DEBUG=false

Thanks.

**Comment by alcarazolabs** [comment]
> I recommend you start from scratch - create a new project and make sure you can access the backup panel in the production environment using a constraint on the user's email first. Then add other packages for permissions.

### Fixed
When I did:
`$ php artisan laravel-backup-panel:install`
It never registered the provider: ` App\Providers\LaravelBackupPanelServiceProvider::class,`
I manually had that register it, and now works :)

The package works with laravel spatie permission, there is not problems with @can middleware.
Thanks so much.

**Comment by pavel-mironchik** [comment]
It's good to know that you finally solved the issue!

Here is how the package registers its service provider using the installation command: https://github.com/pavel-mironchik/laravel-backup-panel/blob/master/src/Console/InstallCommand.php#L68-L72

You may check if there is something different in your `config/app.php` file that could prevent it find and replace the appropriate line.

**Comment by alcarazolabs** [comment]
> It's good to know that you finally solved the issue!
> 
> Here is how the package registers its service provider using the installation command: https://github.com/pavel-mironchik/laravel-backup-panel/blob/master/src/Console/InstallCommand.php#L68-L72
> 
> You may check if there is something different in your `config/app.php` file that could prevent it find and replace the appropriate line.

Thanks so much.. last question sir.. how I can do that only auth users can access to the route backup/? I don't want specify a specific email.

```
Gate::define('viewLaravelBackupPanel', function ($user) {
           
            return in_array($user->email, [
                 'myemail@gmail.com'
            ]);
           
        });
```
thanks.

**Comment by pavel-mironchik** [comment]
> how I can do that only auth users can access to the route backup/? I don't want specify a specific email.

Just return `true` in the gate's callback function:

```php
    Gate::define('viewLaravelBackupPanel', function ($user) {
        return true;
    });
```

**Comment by alcarazolabs** [comment]
> > how I can do that only auth users can access to the route backup/? I don't want specify a specific email.
> 
> Just return `true` in the gate's callback function:
> 
> ```
>     Gate::define('viewLaravelBackupPanel', function ($user) {
>         return true;
>     });
> ```

Thanks so much.. Worked as expected.
