### ISSUE TITLE
add middlware custom

### ISSUE THREAD

**Issue by Oxicode** [pavel-mironchik/laravel-backup-panel#35]
please

**Comment by pavel-mironchik** [comment]
Would you please describe in detail your request?

**Comment by Oxicode** [comment]
Por supuesto, la idea es poder añadir Middleware personalizados a la ruta del /admin/backup. Yo uso el paquete tenancy, y para que funcione correctamente a los routes le debo añadir:
<img width="286" alt="image" src="https://user-images.githubusercontent.com/1320709/157083877-4812a554-8beb-46f1-997c-6ff694cbd302.png">

--- 

Of course, my idea is add Middleware custom to route of backup panel. For example, my project use Tenancy package, and for work i need add this:
<img width="286" alt="image" src="https://user-images.githubusercontent.com/1320709/157083877-4812a554-8beb-46f1-997c-6ff694cbd302.png">

Sorry, my english is not good.

**Comment by pavel-mironchik** [comment]
Please correct me if I'm wrong. It seems that you have to assign a middleware to a route of this package. Well, I could set a name for the single package's route, and then you'll be able to attach your middlewares to it in your service provider.

**Comment by Oxicode** [comment]
yes please
