### ISSUE TITLE
Gate not working when also using spatie/laravel-permission

### ISSUE THREAD

**Issue by sydney1** [pavel-mironchik/laravel-backup-panel#4]
There is a conflict when using spatie/laravel-permission alongside the Laravel Backup Panel production gate.

Production gate works as expected on an app that doesn't use laravel-permission.

I've tested on two separate apps using laravel-permission, and it always denies you, even when your email matches.

**Comment by pavel-mironchik** [comment]
Hello. Please provide a repository reproducing an issue. Just adding a `spatie/laravel-permission` and setting up a simple "admin" role with permission doesn't conflict with the production gate.

**Comment by sydney1** [comment]
I can't share the actual repos I was working on because they're for work, but here's a very slimmed down repo that's giving me the same issue

https://github.com/sydney1/smithers

**Comment by pavel-mironchik** [comment]
Thanks for the repository.

Please tell me how did you add the Laravel Backup Panel into your application. Did you do this manually or run the provided artisan command `php artisan laravel-backup-panel:install`?

As part of the installation process that command registers the `app/Providers/LaravelBackupPanelServiceProvider.php` provider in the `config/app.php`. And I don't see this in your config file.

You can simply run that command and your problem will disappear in a moment.

**Comment by sydney1** [comment]
I definitely ran that artisan command because that's how `app/Providers/LaravelBackupPanelServiceProvider.php` and the public assets got in there (I didn't add those files manually).

I ran it again and this time it registered the service provider in `config/app.php`. So for whatever reason, maybe a weird bug on my machine, it wasn't adding to the config file on the first go. Problem solved, thanks so much!

And if anyone else runs into this, just add `App\Providers\LaravelBackupPanelServiceProvider::class` to your `config/app.php` file.

**Comment by pavel-mironchik** [comment]
@sydney1 I am glad we've found a cause and a solution. But you wrote that you experienced such an issue on two of your apps, and I suppose this isn't a coincidence.

These lines add a provider: https://github.com/pavel-mironchik/laravel-backup-panel/blob/master/src/Console/InstallCommand.php#L68-L72.

In your `config/app.php` file should be a "pattern" `EventServiceProvider::class,`, followed by a line break. If in any case there is no leading comma followed by a line break - it will fail.

Could you please check your git history for that file? Was there anything wrong with that "pattern" line **before** you installed Laravel Backup Panel?

**Comment by sydney1** [comment]
Here's what's under the App Service Providers in `config\app.php` on all 3 apps (I copied from one that didn't work, but they all looked/look the same)

```
        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
```

All three of these apps were created on a Windows machine, using Sublime Text 3 within the last 6 months or so

**Comment by pavel-mironchik** [comment]
Thanks. I checked possible places which could cause such an issue but unfortunately didn't find anything. Anyway, I will keep this in mind.
