### ISSUE TITLE
Undefined constant "Spatie\Backup\Tasks\Backup\SIGINT"

### ISSUE THREAD

**Issue by AkmalArzhang** [pavel-mironchik/laravel-backup-panel#43]
When I click on create update, I get the error: Undefined constant "Spatie\Backup\Tasks\Backup\SIGINT". I couldn't figure out, what is wrong.

**Comment by pavel-mironchik** [comment]
Does the `php artisan backup:run` command work without issues?

**Comment by AkmalArzhang** [comment]
Except for the notification part that I haven't configured yet, it works flawlessly. Here is what I see when I run the artisan `backup:run` command:

```
Starting backup...
Dumping database app-master...
Determining files to backup...
Zipping 3542 files and directories...
Created zip containing 3542 files and directories. Size is 67.95 MB
Copying zip to disk named local...
Successfully copied zip to disk named local.
Sending notification failed
Backup completed!
```

**Comment by AkmalArzhang** [comment]
Except for the notification part that I haven't configured yet, it works flawlessly. Here is what I see when I run the artisan `backup:run` command:

`Starting backup...
Dumping database app-master...
Determining files to backup...
Zipping 3542 files and directories...
Created zip containing 3542 files and directories. Size is 67.95 MB
Copying zip to disk named local...
Successfully copied zip to disk named local.
Sending notification failed
Backup completed!`

**Comment by pavel-mironchik** [comment]
Can you prepare a repository that I can use to recreate the issue?

**Comment by pavel-mironchik** [comment]
Closed as stale.

**Comment by pavel-mironchik** [comment]
https://github.com/spatie/laravel-backup/issues/1445
