### ISSUE TITLE
The dump process failed with a none successful exitcode.

### ISSUE THREAD

**Issue by otatechie** [pavel-mironchik/laravel-backup-panel#44]
Hello, thanks for the package. Am able to successfully create a files backup but when I try to create a database backup, I get 

` Exitcode ======== 127: Command not found Output ====== <no output> Error Output ============ sh: mysqldump: command not found`

**Comment by pavel-mironchik** [comment]
Does the `php artisan backup:run` command work without issues?

**Comment by otatechie** [comment]
Yes @pavel-mironchik it works fine

**Comment by pavel-mironchik** [comment]
Can you prepare a repository that I can use to reproduce the issue?

**Comment by otatechie** [comment]
Okay let me create one

**Comment by otatechie** [comment]
@pavel-mironchik please this is the link [laravel backup issue](https://github.com/thehappytechie/laravel_backup_issue.git)

**Comment by otatechie** [comment]
@pavel-mironchik any feedback regarding this issue, please?

**Comment by pavel-mironchik** [comment]
Not yet.
Did you find out the cause?

**Comment by pavel-mironchik** [comment]
https://github.com/spatie/laravel-backup/issues/1445

**Comment by pavel-mironchik** [comment]
Can't reproduce the issue. I'm not sure but probably a php-fpm (or a user it runs by) hasn't access to the `mysqldump` binary. Or it is SELinux, or else. Anyway, this issue isn't related to the package.
