### ISSUE TITLE
Unable to download backup (file size 270mb)

### ISSUE THREAD

**Issue by DarpanKulkarni** [pavel-mironchik/laravel-backup-panel#45]
Download works for small file like only db but when I click download button on large file (270mb) it shows following error:

Error 503. Service Unavailable

The server is temporarily unavailable. Please check back shortly. If this problem persists, please contact our Technical Support department.

**Comment by pavel-mironchik** [comment]
Do you have suggestions on how to fix this?

**Comment by pavel-mironchik** [comment]
This is a well-known (and still unresolved) issue in Laravel: https://github.com/laravel/framework/issues/31159

You may propose a PR fixing that issue.
