### ISSUE TITLE
Error when restoring a database after backup - pg_restore: error: input file appears to be a text format dump. Please use psql.

### ISSUE THREAD

**Issue by alcarazolabs** [pavel-mironchik/laravel-backup-panel#46]
Hi dear,
After create one backup by using laravel backup panel and import it by using pgadmin because my database is a postgresql it throwed one error:
`pg_restore: error: input file appears to be a text format dump. Please use psql.
`
My DB_CONNECTION is =pgsql
Before I installed laravel backup from spatie v6.
By the moment the backups are being done successfully but when I try to restore a database by using this backup pgadmin v4 is throwing the error of above.

I don't know what to do, in local mode I'm working with mysql database but in production I'm using postgresql.
This issue is with this package or with Laravel-backup from spatie.

I will appreciate any idea to fix this problem.
thanks.

![image](https://user-images.githubusercontent.com/7144988/206581550-f6aa3781-d551-4d44-a889-bf3f04aa4a2d.png)

**Comment by pavel-mironchik** [comment]
Hello. Try creating a backup by running the `php artisan backup:run` in the terminal, and then restore that backup.

**Comment by alcarazolabs** [comment]
> Hello. Try creating a backup by running the `php artisan backup:run` in the terminal, and then restore that backup.

Hi, I did that in windows, I could do the backup but now pgadmin is throwing this error:

`pg_restore: error: input file does not appear to be a valid archive`

Here is a part of code of the backup file:
```
--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1
-- Dumped by pg_dump version 15.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);
```
And when I deployed again the app in a linux server this is throwing this error after doing the backup:

`pg_restore: error: input file appears to be a text format dump. Please use psql.
`

This backup was done with laravel-backup-panel.

In both cases I have problem, I don't know what to do.
thanks.

**Comment by alcarazolabs** [comment]
I fixed the problem adding this:

        'pgsql' => [
            .....
            'dump' => [
                'add_extra_option' => '--format=c -x --no-privileges --no-owner --no-acl -Ft', // and any other pg_dump flags
            ]

most important flag is --format=c  to prevent save the backup in plain text.
