### ISSUE TITLE
unable to get local backuplist

### ISSUE THREAD

**Issue by Kokil** [pavel-mironchik/laravel-backup-panel#48]
I an using laravel 9 and my backup:list shows the backup but it dont shows the backup and disk is backups.

![image](https://user-images.githubusercontent.com/481786/224536167-3598900e-7cfe-4ca7-a16c-96c73984f5a6.png)
![image](https://user-images.githubusercontent.com/481786/224536201-3641c83f-1c28-49c0-ac65-38de0c79af25.png)
![image](https://user-images.githubusercontent.com/481786/224536228-bbd28419-8bca-4c3b-a548-1e010a051f28.png)

**Comment by pavel-mironchik** [comment]
Any errors in Laravel logs or in the browser developer tools?
