### ISSUE TITLE
Listeners not available

### ISSUE THREAD

**Issue by aswinghosh-2hats** [pavel-mironchik/laravel-backup-panel#49]
I am using livewire powergrid for displaying backup files. I am unable to call downloadFile from powergrid component.

**Comment by pavel-mironchik** [comment]
I don't know how the livewire powergrid works. Do you have any suggestions for how to enable the package to work with the livewire powergrid?

**Comment by aswinghosh-2hats** [comment]
If you add listeners for actions like showDeleteModal, downloadFile we can emit these from any component, not just power-grid.

**Comment by pavel-mironchik** [comment]
I will gladly accept a PR with tests that implements such things.
