### ISSUE TITLE
Trait 'Illuminate\Console\DetectsApplicationNamespace' not found

### ISSUE THREAD

**Issue by ahmadeyamin** [pavel-mironchik/laravel-backup-panel#5]
please upgrade for laravel 7 :)

https://github.com/laravel/framework/commit/8725e9665f143aeb18a07aa170398f829cfa6688#diff-c17f57d8e225ed7ad5c603b4944c94dc

**Comment by pavel-mironchik** [comment]
Thanks. Will do definitely.

**Comment by pavel-mironchik** [comment]
Done. Please check with your projects, I don't have one with L7 yet.
