### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by andrersilva96** [pavel-mironchik/laravel-backup-panel#50]
Hello, could you help me?

I'm a little confused between your package and spatie's.

When I configure my "QUEUE_CONNECTION" with "sync" in this case it works if i put "redis" doesn't work.

Is there any way that can I use your package by configuring it to use com redis?

**Comment by pavel-mironchik** [comment]
This package is just a user interface for the spatie's Laravel backup. It itself has nothing with Laravel queues.

You problem is probably you didn't setup a PHP worker. It well described in the Laravel documentation.
