### ISSUE TITLE
Customize view

### ISSUE THREAD

**Issue by borisjer** [pavel-mironchik/laravel-backup-panel#9]
Is there an option to customize view? So it can be fitted in existing application layout. 

Maybe publish --tag=views

**Comment by pavel-mironchik** [comment]
Unfortunately, not. At least for now.

The backup panel that you see in a browser is actually a VueJS single page application, compiled assets. So you just get compiled, minified `app.js` and `app.css` files. And I don't see a suitable way to allow users to customize them.

Even if I allow to publish and change CSS styles, then you'll need to compile and place them into public directory yourself. And when I change something in JavaScript code or CSS - you'll need to figure out what was actually changed and update your custom styles appropriately, just for the fancy look. Is this worth it?

The same approach is used in the Laravel Horizon package and I didn't see anyone requesting a customization feature.

Still, I open to suggestions. If you have an idea of how it could be done - please let me now.

**Comment by borisjer** [comment]
Thanks for the fast response. 

Maybe just include option in layout without customization. 

I wanted to show a backup panel inside the layout with navigation and other stuff. This way it goes to custom page without navigation so the user needs to click the browser back button to return in the application itself.

**Comment by pavel-mironchik** [comment]
May you please try this approach and then let me know if it works?

```html
<iframe src="/backup" frameborder="0"></iframe>
```

Place an iframe inside your layout, e.g. in a `/backupManager` route. Then you'll have your layout with navigation working and Laravel Backup Panel will work "on its own" in an iframe.

**Comment by borisjer** [comment]
That will do. Thanks

**Comment by AEK-BKF** [comment]
It's a great idea to make custom view for blade template.
Hope you do it soon :)

**Comment by pavel-mironchik** [comment]
> It's a great idea to make custom view for blade template.
> Hope you do it soon :)

Please refer to my previous messages in this issue, which describe why it is practically impossible. But if you have an idea of how it could be done - let's discuss it.

**Comment by pavel-mironchik** [comment]
In version 2 you may customize the layout and styles.
